// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("xGherkin.net")]
[assembly: AssemblyDescriptionAttribute("xGherkin.net is a xspec flavored BDD framework, which tries to strike balance between xspec and xbehave nature. The basic goal of this project is to remain close to plain gherkin as much as feasible given the language constrain (given that we are using c# to write gherkin).")]
[assembly: GuidAttribute("119618c8-98cd-477a-b42f-295256cc95a5")]
[assembly: AssemblyProductAttribute("xGherkin.net")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2014 - Nripendra Nath Newa")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.0.4")]
[assembly: AssemblyInformationalVersionAttribute("1.0.4")]
[assembly: AssemblyFileVersionAttribute("1.0.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.4";
    }
}
